name: Photologic-Experiment-Rig-API-Docs

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - master
    # Alternative: only build for tags.
    # tags:
    #   - '*'

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # ADJUST THIS: install all dependencies (including pdoc)
      - run: pip install -r 'Code/Photologic Rig Main Application Code/requirements.txt'
      
      # ADJUST THIS: build your documentation into docs/.
      # We use a custom build script for pdoc itself, ideally you just run `pdoc -o docs/ ...` here.
      - run: mkdir tmp_docs/
      - run: PY_FILES=$(find 'Code/Photologic Rig Main Application Code/src/' -type f -name "*.py")
            echo "PY_FILES=$PY_FILES" >> $GITHUB_ENV

      - run: echo $PY_FILES  &&
          pdoc -o tmp_docs/ $PY_FILES
          
      - run: ls -R tmp_docs
      
      
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: tmp_docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
